// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "fe27afde-a8e4-4993-9229-715ef674fa90");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1654685712);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1654685952);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1654685832);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"131237\":1654685705121,\"131238\":1654685705129,\"131251\":1654685705117}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{1fd061b9-3310-4915-8466-a4d3e59d4743}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1654685749230");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1654687573230");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1654685701680");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1654707301680");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20201221152838");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1654685685");
user_pref("browser.startup.homepage_override.buildID", "20201221152838");
user_pref("browser.startup.homepage_override.mstone", "84.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1656275255);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yahoo!");
user_pref("distribution.iniFile.exists.appversion", "84.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "1c4382375dc246e5a65fd0ab979cfffb");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20201221152838");
user_pref("extensions.lastAppVersion", "84.0.1");
user_pref("extensions.lastPlatformVersion", "84.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b5c92f7c-44dd-43b5-a52f-c8f25cce265a\",\"formautofill@mozilla.org\":\"c1ded927-cb9b-413a-b101-1c0ffdfc5d23\",\"screenshots@mozilla.org\":\"9996ad85-2502-4929-8292-896c75365b70\",\"webcompat-reporter@mozilla.org\":\"f1f7b9b0-2465-4f25-9465-8ddd212e1781\",\"webcompat@mozilla.org\":\"f63dac1d-ff95-40d9-8519-88e1eee1755e\",\"default-theme@mozilla.org\":\"d74da154-d883-468b-baa2-093aab367d83\",\"yahoo@search.mozilla.org\":\"16c92eb5-19d9-45d1-9f60-9ec3afec6ae3\",\"startpage@search.mozilla.org\":\"602e4a5e-cedb-413c-832f-85f1abd8e9bb\",\"duckduckgo@search.mozilla.org\":\"d01d8467-aee2-4a48-a2d3-43de8204be9f\",\"wikipedia@search.mozilla.org\":\"6c89450a-f5bf-4e19-b218-467927611892\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1654685799);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20201221152838");
user_pref("media.gmp-manager.lastCheck", 1654685790);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1654685789);
user_pref("security.remote_settings.intermediates.checked", 1654685789);
user_pref("security.sandbox.content.tempDirSuffix", "715667ea-219c-41e5-82c3-2b6c4415e52c");
user_pref("security.sandbox.plugin.tempDirSuffix", "a437f139-5a7f-452e-96d2-655029dea614");
user_pref("services.blocklist.addons-mlbf.checked", 1654685789);
user_pref("services.blocklist.gfx.checked", 1654685789);
user_pref("services.blocklist.plugins.checked", 1654685789);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1654671434182\"");
user_pref("services.settings.last_update_seconds", 1654685789);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1654685789);
user_pref("services.settings.main.cfr.last_check", 1654685789);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1654685789);
user_pref("services.settings.main.hijack-blocklists.last_check", 1654685789);
user_pref("services.settings.main.language-dictionaries.last_check", 1654685789);
user_pref("services.settings.main.message-groups.last_check", 1654685789);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1654685789);
user_pref("services.settings.main.partitioning-exempt-urls.last_check", 1654685789);
user_pref("services.settings.main.password-recipes.last_check", 1654685789);
user_pref("services.settings.main.pioneer-study-addons-v1.last_check", 1654685789);
user_pref("services.settings.main.public-suffix-list.last_check", 1654685789);
user_pref("services.settings.main.search-config.last_check", 1654685789);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1654685789);
user_pref("services.settings.main.search-telemetry.last_check", 1654685789);
user_pref("services.settings.main.sites-classification.last_check", 1654685789);
user_pref("services.settings.main.top-sites.last_check", 1654685789);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1654685789);
user_pref("services.settings.main.whats-new-panel.last_check", 1654685789);
user_pref("services.settings.security.onecrl.checked", 1654685789);
user_pref("toolkit.startup.last_success", 1656275252);
user_pref("toolkit.telemetry.cachedClientID", "37502392-a316-45d0-9da7-ac549dba76b6");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
